# Base language is Python, but that does not work on macOs & Windows builds
language: python

services:
  - docker

matrix:
  include:
    - name: "IronPython 2.7: Windows"
      os: windows
      language: shell
      before_install:
        - "$ProgramW6432/Docker/Docker/DockerCli" -Version
        - "$ProgramW6432/Docker/Docker/DockerCli" -SwitchLinuxEngine
        - choco install ironpython
      env: PYTHON_IMPL=ironpython PYTHON_VERSION=2.7
    - name: "Python 2.7: Windows"
      os: windows
      language: shell
      before_install:
        - "$ProgramW6432/Docker/Docker/DockerCli" -SwitchLinuxEngine
        - choco install python2 vcredist2008
        - choco install --ignore-dependencies vcpython27
        - pip install pypiwin32
      env: PYTHON_IMPL=cpython PYTHON_VERSION=2.7 PATH=/c/Python27:/c/Python27/Scripts:$PATH
    - name: "Python 3.7: Windows"
      os: windows
      language: shell
      before_install:
        - "$ProgramW6432/Docker/Docker/DockerCli" -SwitchLinuxEngine
        - choco install python
        - pip install pypiwin32
      env: PYTHON_IMPL=cpython PYTHON_VERSION=3.7 PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 2.7: Xenial Linux"
      python: 2.7
      dist: xenial
      env: PYTHON_IMPL=cpython PYTHON_VERSION=2.7
    - name: "Python 3.6: Xenial Linux"
      python: 3.6
      dist: xenial
      env: PYTHON_IMPL=cpython PYTHON_VERSION=3.6
    - name: "Python 3.7: Xenial Linux"
      python: 3.7
      dist: xenial
      env: PYTHON_IMPL=cpython PYTHON_VERSION=3.7

install:
  - docker run -d -p 9090:9090 --name rosbridge gramaziokohler/rosbridge:integration-test /bin/bash -c "roslaunch rosbridge_server rosbridge_websocket.launch"
  - docker ps -a
  - pip install -r requirements-dev.txt

script:
  - python tests/test_param.py

after_script:
  - docker rm -f rosbridge
